import type { AssetType } from "./assets";

import { getMimeType } from "hono/utils/mime";
import { debug } from "../cli/logger";
import { wait } from "../scheduler/scheduler";

let csrfToken = "";
let robloxToken = "";

export function setRobloxToken(token: string) {
	robloxToken = token;
}

export const robloxFetch = async (url: string, init?: RequestInit) => {
	let attempts = 0;
	let lastResponse: Response | undefined;

	while (attempts < 3) {
		attempts++;

		const request = new Request(url, init);
		if (csrfToken) {
			request.headers.set("X-CSRF-Token", csrfToken);
		}
		request.headers.set("Cookie", `.ROBLOSECURITY=${robloxToken}`);
		request.headers.set("User-Agent", "Roblox/WinInet");
		request.headers.set("Accept", "application/json");
		const response = await fetch(request);

		const suggestedCsrf = response.headers.get("X-CSRF-Token");

		if (suggestedCsrf && suggestedCsrf !== csrfToken) {
			csrfToken = suggestedCsrf;
			continue;
		}

		if (response.status === 403) {
			lastResponse = response;
			continue;
		}

		if (!response.ok) {
			debug(await response.text());
			throw response;
		}

		return response;
	}

	throw lastResponse;
};

export async function getUserInfo() {
	const response = await robloxFetch("https://users.roblox.com/v1/users/authenticated");

	const json = await response.json();

	return json as {
		id: number;
		name: string;
		displayName: string;
	};
}

type Asset = {
	assetType: AssetType;
	displayName: string;
	description: string;
	assetId?: number;
	creationContext: {
		creator:
			| {
					userId: string;
			  }
			| {
					groupId: string;
			  };
		expectedPrice: number;
	};
};

type OperationResponse = {
	path: string;
	done: boolean;
	response?: Asset;
	error: any;
	operationId: string;
};

export async function uploadAsset(data: {
	id?: string;
	type: AssetType;
	blob: Uint8Array;
	assetName: string;
	fileName: string;
}): Promise<{ id: number }> {
	const uploadUrl = `https://apis.roblox.com/assets/user-auth/v1/assets`;
	const formData = new FormData();
	const userId = (await getUserInfo()).id;

	const props: Asset = {
		assetType: data.type,
		displayName: data.assetName,
		description: "An asset auto-generated by tk",
		creationContext: {
			creator: {
				userId: userId.toString(),
			},
			expectedPrice: 0,
		},
	};

	debug(props);

	formData.set(
		"fileContent",
		new Blob([data.blob], {
			type: getMimeType(data.fileName),
		}),
		data.fileName,
	);
	formData.set("request", JSON.stringify(props));

	const response = await robloxFetch(uploadUrl, {
		body: formData,
		method: "POST",
		headers: {},
	});

	let result = (await response.json()) as OperationResponse;
	const { operationId } = result;

	let waitPeriod = 500;

	while (!result.response?.assetId) {
		if (result.error) {
			throw result.error.message;
		}
		debug(result, result.response);
		if (waitPeriod > 8000) {
			throw new Error("Operation taking forever");
		}
		await wait(waitPeriod);
		waitPeriod *= 2;
		result = (await (
			await robloxFetch(`https://apis.roblox.com/assets/user-auth/v1/operations/${operationId}`)
		).json()) as OperationResponse;
	}

	return {
		id: result.response!.assetId!,
	};
}
